import{a as w,S as L,i as E}from"./assets/vendor-b11e2a50.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const u of o.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&a(u)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const v="45152595-000e166ccff08e1330e527827",I="https://pixabay.com/api/";async function p(t,r=1,s=15){try{const a=await w.get(`${I}`,{params:{key:v,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:s}});if(a.status!==200)throw new Error("Failed to fetch images");return a.data}catch{throw new Error("Failed to fetch images")}}let f;function h(t,r=!1){const s=document.getElementById("gallery"),a=t.map(e=>`
    <li class="gallery-item">
      <a href="${e.largeImageURL}">
        <img src="${e.webformatURL}" alt="${e.tags}" />
      </a>
      <div class="info">
        <p><b>Likes</b> ${e.likes}</p>
        <p><b>Views</b> ${e.views}</p>
        <p><b>Comments</b> ${e.comments}</p>
        <p><b>Downloads</b> ${e.downloads}</p>
      </div>
    </li>
  `).join("");r?s.insertAdjacentHTML("beforeend",a):s.innerHTML=a,f?f.refresh():f=new L(".gallery-item a",{captions:!0,captionSelector:"img",captionType:"attr",captionsData:"alt",captionPosition:"bottom",captionDelay:250})}function n(t,r="success"){E[r]({title:r==="success"?"OK":"Error",message:t,position:"topRight"})}function B(){const t=document.getElementById("gallery");t.innerHTML=""}function g(){const t=document.getElementById("loader");t.style.display="block"}function b(){const t=document.getElementById("loader");t.style.display="none"}let l="",i=1;const m=15;let c=0;const y=document.getElementById("search-form"),d=document.getElementById("load-more");document.getElementById("loader");y.addEventListener("submit",async t=>{if(t.preventDefault(),l=y.searchQuery.value.trim(),l===""){n("Please enter a search query.","error");return}i=1,B(),d.style.display="none",g();try{const r=await p(l,i,m);c=r.totalHits,c===0?n("Sorry, there are no images matching your search query. Please try again!","error"):(h(r.hits,!1),r.hits.length<c&&(d.style.display="block"))}catch{n("Failed to fetch images. Please try again later.","error")}finally{b()}y.searchQuery.value=""});d.addEventListener("click",async()=>{i+=1,g();try{const t=await p(l,i,m);h(t.hits,!0);const{height:r}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"}),i*m>=c&&(d.style.display="none",n("We're sorry, but you've reached the end of search results.","info"))}catch{n("Failed to fetch images. Please try again later.","error")}finally{b()}});
//# sourceMappingURL=commonHelpers.js.map
